package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL11} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL11 extends org.lwjgl.opengl.GL11 {
	protected GL11() {
	}

	public static void glDisable(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDisable(a0);
			return;
		}
		org.lwjgl.opengl.GL11.glDisable(a0);
	}

	public static void glEnable(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glEnable(a0);
			return;
		}
		org.lwjgl.opengl.GL11.glEnable(a0);
	}
}
