package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL20C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL20C extends org.lwjgl.opengl.GL20C {
	protected GL20C() {
	}

	public static int glGetInteger(final int a0) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetInteger(a0);
		}
		return org.lwjgl.opengl.GL20C.glGetInteger(a0);
	}

	public static int glGetProgrami(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetProgrami(a0, a1);
		}
		return org.lwjgl.opengl.GL20C.glGetProgrami(a0, a1);
	}
}
