package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL30C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL30C extends org.lwjgl.opengl.GL30C {
	protected GL30C() {
	}

	public static void glBindTexture(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindTexture(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL30C.glBindTexture(a0, a1);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final double[] a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final float[] a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int[] a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final java.nio.ByteBuffer a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final java.nio.DoubleBuffer a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final java.nio.FloatBuffer a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final java.nio.IntBuffer a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final java.nio.ShortBuffer a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final long a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage1D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final short[] a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage1D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final double[] a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final float[] a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final int[] a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final java.nio.ByteBuffer a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final java.nio.DoubleBuffer a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final java.nio.FloatBuffer a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final java.nio.IntBuffer a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final java.nio.ShortBuffer a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final long a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glTexImage3D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final short[] a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL30C.glTexImage3D(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}
}
