package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL31C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL31C extends org.lwjgl.opengl.GL31C {
	protected GL31C() {
	}

	public static int glGetUniformBlockIndex(final int a0, final java.lang.CharSequence a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetUniformBlockIndex(a0, a1);
		}
		return org.lwjgl.opengl.GL31C.glGetUniformBlockIndex(a0, a1);
	}

	public static int glGetUniformBlockIndex(final int a0, final java.nio.ByteBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetUniformBlockIndex(a0, a1);
		}
		return org.lwjgl.opengl.GL31C.glGetUniformBlockIndex(a0, a1);
	}

	public static void glUniformBlockBinding(final int a0, final int a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniformBlockBinding(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL31C.glUniformBlockBinding(a0, a1, a2);
	}
}
