package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL32C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL32C extends org.lwjgl.opengl.GL32C {
	protected GL32C() {
	}

	public static void glBindAttribLocation(final int a0, final int a1, final java.lang.CharSequence a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindAttribLocation(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBindAttribLocation(a0, a1, a2);
	}

	public static void glBindAttribLocation(final int a0, final int a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindAttribLocation(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBindAttribLocation(a0, a1, a2);
	}

	public static void glBlitFramebuffer(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final int a9) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBlitFramebuffer(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
			return;
		}
		org.lwjgl.opengl.GL32C.glBlitFramebuffer(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
	}

	public static void glBufferData(final int a0, final double[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final float[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final int[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final java.nio.ByteBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final java.nio.DoubleBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final java.nio.FloatBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final java.nio.IntBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final java.nio.LongBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final java.nio.ShortBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final long a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final long[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glBufferData(final int a0, final short[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glBufferData(a0, a1, a2);
	}

	public static void glClearBufferfv(final int a0, final int a1, final float[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferfv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glClearBufferfv(a0, a1, a2);
	}

	public static void glClearBufferfv(final int a0, final int a1, final java.nio.FloatBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferfv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glClearBufferfv(a0, a1, a2);
	}

	public static void glClearBufferiv(final int a0, final int a1, final int[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferiv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glClearBufferiv(a0, a1, a2);
	}

	public static void glClearBufferiv(final int a0, final int a1, final java.nio.IntBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferiv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glClearBufferiv(a0, a1, a2);
	}

	public static void glClearBufferuiv(final int a0, final int a1, final int[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferuiv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glClearBufferuiv(a0, a1, a2);
	}

	public static void glClearBufferuiv(final int a0, final int a1, final java.nio.IntBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferuiv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glClearBufferuiv(a0, a1, a2);
	}

	public static void glCopyTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glCopyTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL32C.glCopyTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glCopyTexSubImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glCopyTexSubImage2D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL32C.glCopyTexSubImage2D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glDetachShader(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDetachShader(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32C.glDetachShader(a0, a1);
	}

	public static void glDisablei(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDisablei(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32C.glDisablei(a0, a1);
	}

	public static void glDrawBuffers(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL32C.glDrawBuffers(a0);
	}

	public static void glDrawBuffers(final int[] a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL32C.glDrawBuffers(a0);
	}

	public static void glDrawBuffers(final java.nio.IntBuffer a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL32C.glDrawBuffers(a0);
	}

	public static void glEnablei(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glEnablei(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32C.glEnablei(a0, a1);
	}

	public static void glFramebufferTexture2D(final int a0, final int a1, final int a2, final int a3, final int a4) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glFramebufferTexture2D(a0, a1, a2, a3, a4);
			return;
		}
		org.lwjgl.opengl.GL32C.glFramebufferTexture2D(a0, a1, a2, a3, a4);
	}

	public static void glGenerateMipmap(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGenerateMipmap(a0);
			return;
		}
		org.lwjgl.opengl.GL32C.glGenerateMipmap(a0);
	}

	public static java.lang.String glGetActiveUniform(final int a0, final int a1, final int a2, final java.nio.IntBuffer a3, final java.nio.IntBuffer a4) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetActiveUniform(a0, a1, a2, a3, a4);
		}
		return org.lwjgl.opengl.GL32C.glGetActiveUniform(a0, a1, a2, a3, a4);
	}

	public static java.lang.String glGetActiveUniform(final int a0, final int a1, final java.nio.IntBuffer a2, final java.nio.IntBuffer a3) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetActiveUniform(a0, a1, a2, a3);
		}
		return org.lwjgl.opengl.GL32C.glGetActiveUniform(a0, a1, a2, a3);
	}

	public static void glGetActiveUniform(final int a0, final int a1, final int[] a2, final int[] a3, final int[] a4, final java.nio.ByteBuffer a5) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetActiveUniform(a0, a1, a2, a3, a4, a5);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetActiveUniform(a0, a1, a2, a3, a4, a5);
	}

	public static void glGetActiveUniform(final int a0, final int a1, final java.nio.IntBuffer a2, final java.nio.IntBuffer a3, final java.nio.IntBuffer a4, final java.nio.ByteBuffer a5) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetActiveUniform(a0, a1, a2, a3, a4, a5);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetActiveUniform(a0, a1, a2, a3, a4, a5);
	}

	public static void glGetFloatv(final int a0, final float[] a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetFloatv(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetFloatv(a0, a1);
	}

	public static void glGetFloatv(final int a0, final java.nio.FloatBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetFloatv(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetFloatv(a0, a1);
	}

	public static int glGetInteger(final int a0) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetInteger(a0);
		}
		return org.lwjgl.opengl.GL32C.glGetInteger(a0);
	}

	public static void glGetIntegerv(final int a0, final int[] a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetIntegerv(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetIntegerv(a0, a1);
	}

	public static void glGetIntegerv(final int a0, final java.nio.IntBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetIntegerv(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetIntegerv(a0, a1);
	}

	public static java.lang.String glGetProgramInfoLog(final int a0) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetProgramInfoLog(a0);
		}
		return org.lwjgl.opengl.GL32C.glGetProgramInfoLog(a0);
	}

	public static java.lang.String glGetProgramInfoLog(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetProgramInfoLog(a0, a1);
		}
		return org.lwjgl.opengl.GL32C.glGetProgramInfoLog(a0, a1);
	}

	public static void glGetProgramInfoLog(final int a0, final int[] a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetProgramInfoLog(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetProgramInfoLog(a0, a1, a2);
	}

	public static void glGetProgramInfoLog(final int a0, final java.nio.IntBuffer a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetProgramInfoLog(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetProgramInfoLog(a0, a1, a2);
	}

	public static void glGetProgramiv(final int a0, final int a1, final int[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetProgramiv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetProgramiv(a0, a1, a2);
	}

	public static void glGetProgramiv(final int a0, final int a1, final java.nio.IntBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetProgramiv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetProgramiv(a0, a1, a2);
	}

	public static java.lang.String glGetShaderInfoLog(final int a0) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetShaderInfoLog(a0);
		}
		return org.lwjgl.opengl.GL32C.glGetShaderInfoLog(a0);
	}

	public static java.lang.String glGetShaderInfoLog(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetShaderInfoLog(a0, a1);
		}
		return org.lwjgl.opengl.GL32C.glGetShaderInfoLog(a0, a1);
	}

	public static void glGetShaderInfoLog(final int a0, final int[] a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetShaderInfoLog(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetShaderInfoLog(a0, a1, a2);
	}

	public static void glGetShaderInfoLog(final int a0, final java.nio.IntBuffer a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetShaderInfoLog(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glGetShaderInfoLog(a0, a1, a2);
	}

	public static int glGetTexParameteri(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetTexParameteri(a0, a1);
		}
		return org.lwjgl.opengl.GL32C.glGetTexParameteri(a0, a1);
	}

	public static int glGetUniformBlockIndex(final int a0, final java.lang.CharSequence a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetUniformBlockIndex(a0, a1);
		}
		return org.lwjgl.opengl.GL32C.glGetUniformBlockIndex(a0, a1);
	}

	public static int glGetUniformBlockIndex(final int a0, final java.nio.ByteBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetUniformBlockIndex(a0, a1);
		}
		return org.lwjgl.opengl.GL32C.glGetUniformBlockIndex(a0, a1);
	}

	public static void glReadBuffer(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadBuffer(a0);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadBuffer(a0);
	}

	public static void glReadPixels(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final float[] a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glReadPixels(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int[] a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glReadPixels(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final java.nio.ByteBuffer a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glReadPixels(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final java.nio.FloatBuffer a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glReadPixels(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final java.nio.IntBuffer a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glReadPixels(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final java.nio.ShortBuffer a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glReadPixels(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final long a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glReadPixels(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final short[] a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL32C.glReadPixels(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final double[] a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final float[] a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int[] a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final java.nio.ByteBuffer a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final java.nio.DoubleBuffer a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final java.nio.FloatBuffer a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final java.nio.IntBuffer a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final java.nio.ShortBuffer a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final long a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final short[] a8) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexImage2D(a0, a1, a2, a3, a4, a5, a6, a7, a8);
	}

	public static void glTexParameterf(final int a0, final int a1, final float a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexParameterf(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexParameterf(a0, a1, a2);
	}

	public static void glTexParameteri(final int a0, final int a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexParameteri(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexParameteri(a0, a1, a2);
	}

	public static void glTexParameteriv(final int a0, final int a1, final int[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexParameteriv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexParameteriv(a0, a1, a2);
	}

	public static void glTexParameteriv(final int a0, final int a1, final java.nio.IntBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glTexParameteriv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glTexParameteriv(a0, a1, a2);
	}

	public static void glUniform1f(final int a0, final float a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform1f(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniform1f(a0, a1);
	}

	public static void glUniform2f(final int a0, final float a1, final float a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform2f(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniform2f(a0, a1, a2);
	}

	public static void glUniform2i(final int a0, final int a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform2i(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniform2i(a0, a1, a2);
	}

	public static void glUniform3f(final int a0, final float a1, final float a2, final float a3) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform3f(a0, a1, a2, a3);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniform3f(a0, a1, a2, a3);
	}

	public static void glUniform3i(final int a0, final int a1, final int a2, final int a3) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform3i(a0, a1, a2, a3);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniform3i(a0, a1, a2, a3);
	}

	public static void glUniform4f(final int a0, final float a1, final float a2, final float a3, final float a4) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform4f(a0, a1, a2, a3, a4);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniform4f(a0, a1, a2, a3, a4);
	}

	public static void glUniform4i(final int a0, final int a1, final int a2, final int a3, final int a4) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform4i(a0, a1, a2, a3, a4);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniform4i(a0, a1, a2, a3, a4);
	}

	public static void glUniformBlockBinding(final int a0, final int a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniformBlockBinding(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniformBlockBinding(a0, a1, a2);
	}

	public static void glUniformMatrix4fv(final int a0, final boolean a1, final float[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniformMatrix4fv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniformMatrix4fv(a0, a1, a2);
	}

	public static void glUniformMatrix4fv(final int a0, final boolean a1, final java.nio.FloatBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniformMatrix4fv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32C.glUniformMatrix4fv(a0, a1, a2);
	}

	public static void glUseProgram(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUseProgram(a0);
			return;
		}
		org.lwjgl.opengl.GL32C.glUseProgram(a0);
	}

	public static void glVertexAttrib4f(final int a0, final float a1, final float a2, final float a3, final float a4) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glVertexAttrib4f(a0, a1, a2, a3, a4);
			return;
		}
		org.lwjgl.opengl.GL32C.glVertexAttrib4f(a0, a1, a2, a3, a4);
	}
}
