package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL32} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL32 extends org.lwjgl.opengl.GL32 {
	protected GL32() {
	}

	public static void glBindAttribLocation(final int a0, final int a1, final java.lang.CharSequence a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindAttribLocation(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32.glBindAttribLocation(a0, a1, a2);
	}

	public static void glBindAttribLocation(final int a0, final int a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindAttribLocation(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32.glBindAttribLocation(a0, a1, a2);
	}

	public static void glBindBuffer(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindBuffer(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL32.glBindBuffer(a0, a1);
	}

	public static int glCheckFramebufferStatus(final int a0) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glCheckFramebufferStatus(a0);
		}
		return org.lwjgl.opengl.GL32.glCheckFramebufferStatus(a0);
	}

	public static void glEnableVertexAttribArray(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glEnableVertexAttribArray(a0);
			return;
		}
		org.lwjgl.opengl.GL32.glEnableVertexAttribArray(a0);
	}

	public static java.lang.String glGetProgramInfoLog(final int a0) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetProgramInfoLog(a0);
		}
		return org.lwjgl.opengl.GL32.glGetProgramInfoLog(a0);
	}

	public static java.lang.String glGetProgramInfoLog(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetProgramInfoLog(a0, a1);
		}
		return org.lwjgl.opengl.GL32.glGetProgramInfoLog(a0, a1);
	}

	public static void glGetProgramInfoLog(final int a0, final int[] a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetProgramInfoLog(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32.glGetProgramInfoLog(a0, a1, a2);
	}

	public static void glGetProgramInfoLog(final int a0, final java.nio.IntBuffer a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGetProgramInfoLog(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL32.glGetProgramInfoLog(a0, a1, a2);
	}

	public static int glGetProgrami(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetProgrami(a0, a1);
		}
		return org.lwjgl.opengl.GL32.glGetProgrami(a0, a1);
	}

	public static int glGetUniformLocation(final int a0, final java.lang.CharSequence a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetUniformLocation(a0, a1);
		}
		return org.lwjgl.opengl.GL32.glGetUniformLocation(a0, a1);
	}

	public static int glGetUniformLocation(final int a0, final java.nio.ByteBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetUniformLocation(a0, a1);
		}
		return org.lwjgl.opengl.GL32.glGetUniformLocation(a0, a1);
	}

	public static void glLinkProgram(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glLinkProgram(a0);
			return;
		}
		org.lwjgl.opengl.GL32.glLinkProgram(a0);
	}

	public static void glUseProgram(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUseProgram(a0);
			return;
		}
		org.lwjgl.opengl.GL32.glUseProgram(a0);
	}

	public static void glVertexAttribPointer(final int a0, final int a1, final int a2, final boolean a3, final int a4, final java.nio.ByteBuffer a5) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
			return;
		}
		org.lwjgl.opengl.GL32.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
	}

	public static void glVertexAttribPointer(final int a0, final int a1, final int a2, final boolean a3, final int a4, final java.nio.FloatBuffer a5) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
			return;
		}
		org.lwjgl.opengl.GL32.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
	}

	public static void glVertexAttribPointer(final int a0, final int a1, final int a2, final boolean a3, final int a4, final java.nio.IntBuffer a5) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
			return;
		}
		org.lwjgl.opengl.GL32.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
	}

	public static void glVertexAttribPointer(final int a0, final int a1, final int a2, final boolean a3, final int a4, final java.nio.ShortBuffer a5) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
			return;
		}
		org.lwjgl.opengl.GL32.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
	}

	public static void glVertexAttribPointer(final int a0, final int a1, final int a2, final boolean a3, final int a4, final long a5) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
			return;
		}
		org.lwjgl.opengl.GL32.glVertexAttribPointer(a0, a1, a2, a3, a4, a5);
	}
}
