package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL33C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL33C extends org.lwjgl.opengl.GL33C {
	protected GL33C() {
	}

	public static void glBindSampler(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindSampler(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL33C.glBindSampler(a0, a1);
	}

	public static void glDeleteSamplers(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDeleteSamplers(a0);
			return;
		}
		org.lwjgl.opengl.GL33C.glDeleteSamplers(a0);
	}

	public static void glDeleteSamplers(final int[] a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDeleteSamplers(a0);
			return;
		}
		org.lwjgl.opengl.GL33C.glDeleteSamplers(a0);
	}

	public static void glDeleteSamplers(final java.nio.IntBuffer a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDeleteSamplers(a0);
			return;
		}
		org.lwjgl.opengl.GL33C.glDeleteSamplers(a0);
	}

	public static void glDrawBuffers(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL33C.glDrawBuffers(a0);
	}

	public static void glDrawBuffers(final int[] a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL33C.glDrawBuffers(a0);
	}

	public static void glDrawBuffers(final java.nio.IntBuffer a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL33C.glDrawBuffers(a0);
	}

	public static int glGenSamplers() {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGenSamplers();
		}
		return org.lwjgl.opengl.GL33C.glGenSamplers();
	}

	public static void glGenSamplers(final int[] a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGenSamplers(a0);
			return;
		}
		org.lwjgl.opengl.GL33C.glGenSamplers(a0);
	}

	public static void glGenSamplers(final java.nio.IntBuffer a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGenSamplers(a0);
			return;
		}
		org.lwjgl.opengl.GL33C.glGenSamplers(a0);
	}

	public static int glGetAttribLocation(final int a0, final java.lang.CharSequence a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetAttribLocation(a0, a1);
		}
		return org.lwjgl.opengl.GL33C.glGetAttribLocation(a0, a1);
	}

	public static int glGetAttribLocation(final int a0, final java.nio.ByteBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetAttribLocation(a0, a1);
		}
		return org.lwjgl.opengl.GL33C.glGetAttribLocation(a0, a1);
	}

	public static void glSamplerParameterf(final int a0, final int a1, final float a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glSamplerParameterf(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL33C.glSamplerParameterf(a0, a1, a2);
	}

	public static void glSamplerParameteri(final int a0, final int a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glSamplerParameteri(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL33C.glSamplerParameteri(a0, a1, a2);
	}

	public static void glSamplerParameteriv(final int a0, final int a1, final int[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glSamplerParameteriv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL33C.glSamplerParameteriv(a0, a1, a2);
	}

	public static void glSamplerParameteriv(final int a0, final int a1, final java.nio.IntBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glSamplerParameteriv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL33C.glSamplerParameteriv(a0, a1, a2);
	}
}
