package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL42C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL42C extends org.lwjgl.opengl.GL42C {
	protected GL42C() {
	}

	public static void glBindImageTexture(final int a0, final int a1, final int a2, final boolean a3, final int a4, final int a5, final int a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindImageTexture(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL42C.glBindImageTexture(a0, a1, a2, a3, a4, a5, a6);
	}
}
