package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL43C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL43C extends org.lwjgl.opengl.GL43C {
	protected GL43C() {
	}

	public static void glAttachShader(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glAttachShader(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL43C.glAttachShader(a0, a1);
	}

	public static void glBindBufferBase(final int a0, final int a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindBufferBase(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL43C.glBindBufferBase(a0, a1, a2);
	}

	public static void glClearBufferSubData(final int a0, final int a1, final long a2, final long a3, final int a4, final int a5, final float[] a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL43C.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glClearBufferSubData(final int a0, final int a1, final long a2, final long a3, final int a4, final int a5, final int[] a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL43C.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glClearBufferSubData(final int a0, final int a1, final long a2, final long a3, final int a4, final int a5, final java.nio.ByteBuffer a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL43C.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glClearBufferSubData(final int a0, final int a1, final long a2, final long a3, final int a4, final int a5, final java.nio.FloatBuffer a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL43C.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glClearBufferSubData(final int a0, final int a1, final long a2, final long a3, final int a4, final int a5, final java.nio.IntBuffer a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL43C.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glClearBufferSubData(final int a0, final int a1, final long a2, final long a3, final int a4, final int a5, final java.nio.ShortBuffer a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL43C.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
	}

	public static void glClearBufferSubData(final int a0, final int a1, final long a2, final long a3, final int a4, final int a5, final short[] a6) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
			return;
		}
		org.lwjgl.opengl.GL43C.glClearBufferSubData(a0, a1, a2, a3, a4, a5, a6);
	}

	public static int glCreateProgram() {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glCreateProgram();
		}
		return org.lwjgl.opengl.GL43C.glCreateProgram();
	}

	public static void glDebugMessageCallback(final org.lwjgl.opengl.GLDebugMessageCallbackI a0, final long a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDebugMessageCallback(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL43C.glDebugMessageCallback(a0, a1);
	}

	public static void glDebugMessageControl(final int a0, final int a1, final int a2, final int a3, final boolean a4) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDebugMessageControl(a0, a1, a2, a3, a4);
			return;
		}
		org.lwjgl.opengl.GL43C.glDebugMessageControl(a0, a1, a2, a3, a4);
	}

	public static void glDebugMessageControl(final int a0, final int a1, final int a2, final int[] a3, final boolean a4) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDebugMessageControl(a0, a1, a2, a3, a4);
			return;
		}
		org.lwjgl.opengl.GL43C.glDebugMessageControl(a0, a1, a2, a3, a4);
	}

	public static void glDebugMessageControl(final int a0, final int a1, final int a2, final java.nio.IntBuffer a3, final boolean a4) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDebugMessageControl(a0, a1, a2, a3, a4);
			return;
		}
		org.lwjgl.opengl.GL43C.glDebugMessageControl(a0, a1, a2, a3, a4);
	}

	public static void glDeleteBuffers(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDeleteBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glDeleteBuffers(a0);
	}

	public static void glDeleteBuffers(final int[] a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDeleteBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glDeleteBuffers(a0);
	}

	public static void glDeleteBuffers(final java.nio.IntBuffer a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDeleteBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glDeleteBuffers(a0);
	}

	public static void glDeleteProgram(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDeleteProgram(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glDeleteProgram(a0);
	}

	public static void glDisable(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDisable(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glDisable(a0);
	}

	public static void glDispatchComputeIndirect(final long a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDispatchComputeIndirect(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glDispatchComputeIndirect(a0);
	}

	public static void glDrawElements(final int a0, final int a1, final int a2, final long a3) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawElements(a0, a1, a2, a3);
			return;
		}
		org.lwjgl.opengl.GL43C.glDrawElements(a0, a1, a2, a3);
	}

	public static void glDrawElements(final int a0, final int a1, final java.nio.ByteBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawElements(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL43C.glDrawElements(a0, a1, a2);
	}

	public static void glDrawElements(final int a0, final java.nio.ByteBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawElements(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL43C.glDrawElements(a0, a1);
	}

	public static void glDrawElements(final int a0, final java.nio.IntBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawElements(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL43C.glDrawElements(a0, a1);
	}

	public static void glDrawElements(final int a0, final java.nio.ShortBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDrawElements(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL43C.glDrawElements(a0, a1);
	}

	public static void glEnable(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glEnable(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glEnable(a0);
	}

	public static int glGenBuffers() {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGenBuffers();
		}
		return org.lwjgl.opengl.GL43C.glGenBuffers();
	}

	public static void glGenBuffers(final int[] a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGenBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glGenBuffers(a0);
	}

	public static void glGenBuffers(final java.nio.IntBuffer a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glGenBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glGenBuffers(a0);
	}

	public static int glGetInteger(final int a0) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetInteger(a0);
		}
		return org.lwjgl.opengl.GL43C.glGetInteger(a0);
	}

	public static void glPolygonMode(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glPolygonMode(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL43C.glPolygonMode(a0, a1);
	}

	public static void glUniform1f(final int a0, final float a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform1f(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL43C.glUniform1f(a0, a1);
	}

	public static void glUniform1i(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform1i(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL43C.glUniform1i(a0, a1);
	}

	public static void glUniform3f(final int a0, final float a1, final float a2, final float a3) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform3f(a0, a1, a2, a3);
			return;
		}
		org.lwjgl.opengl.GL43C.glUniform3f(a0, a1, a2, a3);
	}

	public static void glUniform3i(final int a0, final int a1, final int a2, final int a3) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform3i(a0, a1, a2, a3);
			return;
		}
		org.lwjgl.opengl.GL43C.glUniform3i(a0, a1, a2, a3);
	}

	public static void glUseProgram(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUseProgram(a0);
			return;
		}
		org.lwjgl.opengl.GL43C.glUseProgram(a0);
	}
}
