package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL45C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL45C extends org.lwjgl.opengl.GL45C {
	protected GL45C() {
	}

	public static void glBindSamplers(final int a0, final int[] a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindSamplers(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL45C.glBindSamplers(a0, a1);
	}

	public static void glBindSamplers(final int a0, final java.nio.IntBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindSamplers(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL45C.glBindSamplers(a0, a1);
	}

	public static void glBufferStorage(final int a0, final double[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final float[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final int[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final java.nio.ByteBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final java.nio.DoubleBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final java.nio.FloatBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final java.nio.IntBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final java.nio.ShortBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final long a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static void glBufferStorage(final int a0, final short[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBufferStorage(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glBufferStorage(a0, a1, a2);
	}

	public static int glCreateBuffers() {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glCreateBuffers();
		}
		return org.lwjgl.opengl.GL45C.glCreateBuffers();
	}

	public static void glCreateBuffers(final int[] a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glCreateBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL45C.glCreateBuffers(a0);
	}

	public static void glCreateBuffers(final java.nio.IntBuffer a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glCreateBuffers(a0);
			return;
		}
		org.lwjgl.opengl.GL45C.glCreateBuffers(a0);
	}

	public static void glDispatchCompute(final int a0, final int a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glDispatchCompute(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glDispatchCompute(a0, a1, a2);
	}

	public static void glMemoryBarrier(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glMemoryBarrier(a0);
			return;
		}
		org.lwjgl.opengl.GL45C.glMemoryBarrier(a0);
	}

	public static void glNamedBufferData(final int a0, final double[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final float[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final int[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final java.nio.ByteBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final java.nio.DoubleBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final java.nio.FloatBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final java.nio.IntBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final java.nio.LongBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final java.nio.ShortBuffer a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final long a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final long[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}

	public static void glNamedBufferData(final int a0, final short[] a1, final int a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glNamedBufferData(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL45C.glNamedBufferData(a0, a1, a2);
	}
}
