package net.irisshaders.iris.metal.gl;

/**
 * MineMetal facade for {@link org.lwjgl.opengl.GL46C} (GENERATED by tools/gen-facades – do not edit by hand).
 * Iris imports this class instead of the LWJGL one. All constants and untouched functions are inherited; the functions
 * Iris calls are re-declared here and routed to MineMetal's GL emulation when the Metal backend is active.
 */
@SuppressWarnings("unused")
public class GL46C extends org.lwjgl.opengl.GL46C {
	protected GL46C() {
	}

	public static void glBindBuffer(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindBuffer(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL46C.glBindBuffer(a0, a1);
	}

	public static void glBindTexture(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glBindTexture(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL46C.glBindTexture(a0, a1);
	}

	public static int glCheckFramebufferStatus(final int a0) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glCheckFramebufferStatus(a0);
		}
		return org.lwjgl.opengl.GL46C.glCheckFramebufferStatus(a0);
	}

	public static void glClearColor(final float a0, final float a1, final float a2, final float a3) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glClearColor(a0, a1, a2, a3);
			return;
		}
		org.lwjgl.opengl.GL46C.glClearColor(a0, a1, a2, a3);
	}

	public static void glCopyImageSubData(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7, final int a8, final int a9, final int a10, final int a11, final int a12, final int a13, final int a14) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glCopyImageSubData(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14);
			return;
		}
		org.lwjgl.opengl.GL46C.glCopyImageSubData(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14);
	}

	public static void glCopyTexSubImage2D(final int a0, final int a1, final int a2, final int a3, final int a4, final int a5, final int a6, final int a7) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glCopyTexSubImage2D(a0, a1, a2, a3, a4, a5, a6, a7);
			return;
		}
		org.lwjgl.opengl.GL46C.glCopyTexSubImage2D(a0, a1, a2, a3, a4, a5, a6, a7);
	}

	public static void glEnable(final int a0) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glEnable(a0);
			return;
		}
		org.lwjgl.opengl.GL46C.glEnable(a0);
	}

	public static int glGetAttribLocation(final int a0, final java.lang.CharSequence a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetAttribLocation(a0, a1);
		}
		return org.lwjgl.opengl.GL46C.glGetAttribLocation(a0, a1);
	}

	public static int glGetAttribLocation(final int a0, final java.nio.ByteBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetAttribLocation(a0, a1);
		}
		return org.lwjgl.opengl.GL46C.glGetAttribLocation(a0, a1);
	}

	public static java.lang.String glGetStringi(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetStringi(a0, a1);
		}
		return org.lwjgl.opengl.GL46C.glGetStringi(a0, a1);
	}

	public static int glGetUniformBlockIndex(final int a0, final java.lang.CharSequence a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetUniformBlockIndex(a0, a1);
		}
		return org.lwjgl.opengl.GL46C.glGetUniformBlockIndex(a0, a1);
	}

	public static int glGetUniformBlockIndex(final int a0, final java.nio.ByteBuffer a1) {
		if (MetalGlBridge.isMetal()) {
			return dev.minemetal.client.glcompat.GLDispatch.glGetUniformBlockIndex(a0, a1);
		}
		return org.lwjgl.opengl.GL46C.glGetUniformBlockIndex(a0, a1);
	}

	public static void glUniform1f(final int a0, final float a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform1f(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL46C.glUniform1f(a0, a1);
	}

	public static void glUniform1i(final int a0, final int a1) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniform1i(a0, a1);
			return;
		}
		org.lwjgl.opengl.GL46C.glUniform1i(a0, a1);
	}

	public static void glUniformMatrix3fv(final int a0, final boolean a1, final float[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniformMatrix3fv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL46C.glUniformMatrix3fv(a0, a1, a2);
	}

	public static void glUniformMatrix3fv(final int a0, final boolean a1, final java.nio.FloatBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniformMatrix3fv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL46C.glUniformMatrix3fv(a0, a1, a2);
	}

	public static void glUniformMatrix4fv(final int a0, final boolean a1, final float[] a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniformMatrix4fv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL46C.glUniformMatrix4fv(a0, a1, a2);
	}

	public static void glUniformMatrix4fv(final int a0, final boolean a1, final java.nio.FloatBuffer a2) {
		if (MetalGlBridge.isMetal()) {
			dev.minemetal.client.glcompat.GLDispatch.glUniformMatrix4fv(a0, a1, a2);
			return;
		}
		org.lwjgl.opengl.GL46C.glUniformMatrix4fv(a0, a1, a2);
	}
}
